@echo off
if /i "%~1"=="apply" goto apply
if /i "%~1"=="revert" goto revert
exit

:apply
:: Força a GPU AMD a operar no estado de máximo desempenho (P0 / clock máximo)
:: Desativa ULPS para impedir que a GPU entre em ultra low power state
powershell -NoProfile -Command "$gpuClass = 'HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}'; Get-ChildItem $gpuClass -EA SilentlyContinue | Where-Object { $_.PSChildName -match '^\d{4}$' } | ForEach-Object { $pv = (Get-ItemProperty $_.PSPath -Name 'ProviderName' -EA SilentlyContinue).ProviderName; if ($pv -match 'AMD|ATI') { Set-ItemProperty $_.PSPath -Name 'EnableULPS' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'EnableULPS_NA' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'PP_ThermalAutoThrottlingEnable' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'PP_SclkDeepSleepEnable' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'PP_ThermalController' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'KMD_EnableComputePreemption' -Value 0 -Type DWord -EA SilentlyContinue } }"
:: Força máxima performance via política de energia AMD
powershell -NoProfile -Command "$gpuClass = 'HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}'; Get-ChildItem $gpuClass -EA SilentlyContinue | Where-Object { $_.PSChildName -match '^\d{4}$' } | ForEach-Object { $pv = (Get-ItemProperty $_.PSPath -Name 'ProviderName' -EA SilentlyContinue).ProviderName; if ($pv -match 'AMD|ATI') { Set-ItemProperty $_.PSPath -Name 'PP_DisablePowerContainment' -Value 1 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'PP_PowerContainment' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'PP_GpuPowerBoostEnable' -Value 1 -Type DWord -EA SilentlyContinue } }"
:: Força VRAM a permanecer no clock máximo (evita redução de clock de memória)
powershell -NoProfile -Command "$gpuClass = 'HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}'; Get-ChildItem $gpuClass -EA SilentlyContinue | Where-Object { $_.PSChildName -match '^\d{4}$' } | ForEach-Object { $pv = (Get-ItemProperty $_.PSPath -Name 'ProviderName' -EA SilentlyContinue).ProviderName; if ($pv -match 'AMD|ATI') { Set-ItemProperty $_.PSPath -Name 'PP_Force3DPerformanceMode' -Value 1 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'ACE' -Value 0 -Type DWord -EA SilentlyContinue } }"
:: Gerenciamento de energia da GPU via Windows: desativa PnP power management
powershell -NoProfile -Command "Get-PnpDevice | Where-Object { $_.Class -eq 'Display' -and ($_.FriendlyName -match 'AMD|ATI|Radeon') } | ForEach-Object { $devPath = \"HKLM:\SYSTEM\CurrentControlSet\Enum\$($_.InstanceId)\Device Parameters\"; if (Test-Path $devPath) { Set-ItemProperty -Path $devPath -Name 'AllowIdleIrpInD3' -Value 0 -Type DWord -EA SilentlyContinue }; $enumPath = \"HKLM:\SYSTEM\CurrentControlSet\Enum\$($_.InstanceId)\"; if (Test-Path $enumPath) { Set-ItemProperty -Path $enumPath -Name 'EnhancedPowerManagementEnabled' -Value 0 -Type DWord -EA SilentlyContinue } }"
:: Desativa AMD Power Gating (desliga setores inativos da GPU para economizar energia)
:: Desativar evita latência ao religar esses setores e reduz micro-stuttering
powershell -NoProfile -Command "$gpuClass = 'HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}'; Get-ChildItem $gpuClass -EA SilentlyContinue | Where-Object { $_.PSChildName -match '^\d{4}$' } | ForEach-Object { $pv = (Get-ItemProperty $_.PSPath -Name 'ProviderName' -EA SilentlyContinue).ProviderName; if ($pv -match 'AMD|ATI') { Set-ItemProperty $_.PSPath -Name 'PP_PhmUseDummyBackEnd' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'PP_GFXPowerGating' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'PP_UVDPowerGating' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'PP_VCEPowerGating' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'PP_SAMUPowerGating' -Value 0 -Type DWord -EA SilentlyContinue; Set-ItemProperty $_.PSPath -Name 'PP_ACP_PowerGating' -Value 0 -Type DWord -EA SilentlyContinue } }"
exit

:revert
:: Restaura comportamento padrão de gerenciamento de energia da GPU AMD
powershell -NoProfile -Command "$gpuClass = 'HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}'; Get-ChildItem $gpuClass -EA SilentlyContinue | Where-Object { $_.PSChildName -match '^\d{4}$' } | ForEach-Object { $pv = (Get-ItemProperty $_.PSPath -Name 'ProviderName' -EA SilentlyContinue).ProviderName; if ($pv -match 'AMD|ATI') { Set-ItemProperty $_.PSPath -Name 'EnableULPS' -Value 1 -Type DWord -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'EnableULPS_NA' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_ThermalAutoThrottlingEnable' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_SclkDeepSleepEnable' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_ThermalController' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'KMD_EnableComputePreemption' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_DisablePowerContainment' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_PowerContainment' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_GpuPowerBoostEnable' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_Force3DPerformanceMode' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'ACE' -EA SilentlyContinue } }"
:: Reativa AMD Power Gating (padrão do driver)
powershell -NoProfile -Command "$gpuClass = 'HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}'; Get-ChildItem $gpuClass -EA SilentlyContinue | Where-Object { $_.PSChildName -match '^\d{4}$' } | ForEach-Object { $pv = (Get-ItemProperty $_.PSPath -Name 'ProviderName' -EA SilentlyContinue).ProviderName; if ($pv -match 'AMD|ATI') { Remove-ItemProperty $_.PSPath -Name 'PP_PhmUseDummyBackEnd' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_GFXPowerGating' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_UVDPowerGating' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_VCEPowerGating' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_SAMUPowerGating' -EA SilentlyContinue; Remove-ItemProperty $_.PSPath -Name 'PP_ACP_PowerGating' -EA SilentlyContinue } }"
:: Restaura gerenciamento de energia PnP da GPU (configuracoes de dispositivo)
powershell -NoProfile -Command "Get-PnpDevice | Where-Object { $_.Class -eq 'Display' -and ($_.FriendlyName -match 'AMD|ATI|Radeon') } | ForEach-Object { $devPath = \"HKLM:\SYSTEM\CurrentControlSet\Enum\$($_.InstanceId)\Device Parameters\"; if (Test-Path $devPath) { Remove-ItemProperty -Path $devPath -Name 'AllowIdleIrpInD3' -EA SilentlyContinue }; $enumPath = \"HKLM:\SYSTEM\CurrentControlSet\Enum\$($_.InstanceId)\"; if (Test-Path $enumPath) { Remove-ItemProperty -Path $enumPath -Name 'EnhancedPowerManagementEnabled' -EA SilentlyContinue } }"
exit
